app:
    build: .
    environment:
        - LDAP_URL=ldap://ldap:389
        - LDAP_BINDDN=cn=admin,dc=example,dc=com
        - LDAP_BINDPW=secret
        - LDAP_BASE=dc=example,dc=com
        - LDAP_LOGIN_ATTRIBUTE=
        - LDAP_FULLNAME_ATTRIBUTE=
        - LDAP_FILTER=
